vorg.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties
mod_id=raccooncore
mod_name=RaccoonCore
mod_license=GNU General Public License v3.0 (GPLv3)
mod_version=2.3.0
mod_group_id=net.kamkeyke.raccooncore
mod_authors=KamKeyke
mod_description=This library provides the necessary infrastructure for the operation of the mods created by me, Kamkeyke.